// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA29pueBfkY0vbGvZ0a4A3eDJcwypqiGo',
    appId: '1:1051271489868:web:9ae37300ad34befc8f87e9',
    messagingSenderId: '1051271489868',
    projectId: 'cryptoportfolio-dev-d53d7',
    authDomain: 'cryptoportfolio-dev-d53d7.firebaseapp.com',
    storageBucket: 'cryptoportfolio-dev-d53d7.appspot.com',
    measurementId: 'G-DHVSPC8FBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA04Qk-YW5Xbg9mxM76yPo9bYWhZvvMmZ0',
    appId: '1:1051271489868:android:9488b1e6d6569ec78f87e9',
    messagingSenderId: '1051271489868',
    projectId: 'cryptoportfolio-dev-d53d7',
    storageBucket: 'cryptoportfolio-dev-d53d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hDT278QGBBVEHN8WhIdVt0RFli8cagk',
    appId: '1:1051271489868:ios:2d2be79a023864ab8f87e9',
    messagingSenderId: '1051271489868',
    projectId: 'cryptoportfolio-dev-d53d7',
    storageBucket: 'cryptoportfolio-dev-d53d7.appspot.com',
    iosClientId: '1051271489868-qlfkh6imk6ovm267tdt9k2tr12qkpenb.apps.googleusercontent.com',
    iosBundleId: 'com.buvaty.cryptoportfolio.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hDT278QGBBVEHN8WhIdVt0RFli8cagk',
    appId: '1:1051271489868:ios:2d2be79a023864ab8f87e9',
    messagingSenderId: '1051271489868',
    projectId: 'cryptoportfolio-dev-d53d7',
    storageBucket: 'cryptoportfolio-dev-d53d7.appspot.com',
    iosClientId: '1051271489868-qlfkh6imk6ovm267tdt9k2tr12qkpenb.apps.googleusercontent.com',
    iosBundleId: 'com.buvaty.cryptoportfolio.dev',
  );
}
