// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwo0a2gKQ6upw8dPAAM0U_Mt6gEDe3Ng',
    appId: '1:270623990017:web:fe80713ee9a144fa573b00',
    messagingSenderId: '270623990017',
    projectId: 'cryptoportfolio-prod',
    authDomain: 'cryptoportfolio-prod.firebaseapp.com',
    storageBucket: 'cryptoportfolio-prod.appspot.com',
    measurementId: 'G-NNF46QKRKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvZTcHRnLcHcEaVuy-0fRJZnEbbVMJYY',
    appId: '1:270623990017:android:a62c4430f038afa3573b00',
    messagingSenderId: '270623990017',
    projectId: 'cryptoportfolio-prod',
    storageBucket: 'cryptoportfolio-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnFnqANIz_AXuE_7z9oTkuMpo656n7X-s',
    appId: '1:270623990017:ios:d92fc79adcec66a3573b00',
    messagingSenderId: '270623990017',
    projectId: 'cryptoportfolio-prod',
    storageBucket: 'cryptoportfolio-prod.appspot.com',
    iosClientId: '270623990017-gtclv0tjvklu9ku0eic80b32us5ms73p.apps.googleusercontent.com',
    iosBundleId: 'com.buvaty.cryptoportfolio',
  );
}
