// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFV2CTTtFSKx4n75AOQo36zmp1I9YRz9k',
    appId: '1:430805526137:web:4f9a2f3230834a82ffd6a8',
    messagingSenderId: '430805526137',
    projectId: 'cryptoportfolio-stg',
    authDomain: 'cryptoportfolio-stg.firebaseapp.com',
    storageBucket: 'cryptoportfolio-stg.appspot.com',
    measurementId: 'G-WDJ8504M6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOj-RIWVohHmeHrePFRMpDoC7cGF07m_g',
    appId: '1:430805526137:android:21428329b145d820ffd6a8',
    messagingSenderId: '430805526137',
    projectId: 'cryptoportfolio-stg',
    storageBucket: 'cryptoportfolio-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDs8z-fdminrvhBcR3tJG1g5Y9RCOzCQw',
    appId: '1:430805526137:ios:f3c3f73b2a4d79cbffd6a8',
    messagingSenderId: '430805526137',
    projectId: 'cryptoportfolio-stg',
    storageBucket: 'cryptoportfolio-stg.appspot.com',
    iosClientId: '430805526137-rb1fgb6ucrblt27fll7e9esu4dkcmi86.apps.googleusercontent.com',
    iosBundleId: 'com.buvaty.cryptoportfolio.stg',
  );
}
